[[permission]]
identifier = "allow-start-raw-video-session"
description = "Enables the start_raw_video_session command without any pre-configured scope."
commands.allow = ["start_raw_video_session"]

[[permission]]
identifier = "deny-start-raw-video-session"
description = "Denies the start_raw_video_session command without any pre-configured scope."
commands.deny = ["start_raw_video_session"]
